icons = "awesome"

[theme]
name = "solarized-dark"

[theme.overrides]
separator = "<span font='15'></span>"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"
driver = "auto"
on_click = "pavucontrol"

[[block]]
block = "bluetooth"
mac = "2C:41:A1:C9:88:27"
format = ""
format_unavailable = ""

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "net"
device = "enp34s0"
format = "{ip}"
interval = 10
