[icons]
icons = "awesome4"

[theme]
theme = "solarized-dark"

[theme.overrides]
separator = "<span font='15'></span>"

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1

[[block]]
block = "sound"
driver = "auto"

[[block]]
block = "bluetooth"
mac = "78:2B:64:CE:BB:20"
format = ""
disconnected_format = ""

[[block]]
block = "music"
player = "spotify"
format = " $icon {$combo.str(max_w:20) $play $next |}"

[[block]]
block = "time"
interval = 10
[block.format]
short = " $icon $timestamp.datetime(f:%R) "

[[block]]
block = "tea_timer"
format = " $icon {$minutes:$seconds |}"
done_cmd = "notify-send 'Timer Finished'"

[[block]]
block = "net"
format = " $icon "
device = "enp34s0"
