icons = "awesome"

[theme]
name = "solarized-dark"

[theme.overrides]
separator = "<span font='15'></span>"

[[block]]
block = "battery"
driver = "upower"
interval = 60

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"
driver = "auto"
on_click = "pavucontrol"

[[block]]
block = "bluetooth"
mac = "2C:41:A1:C9:88:27"

[[block]]
block = "music"
player = "spotify"
marquee = false
buttons = ["play", "next"]
on_collapsed_click = "spotify"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
signal_strength = true
speed_up = false
speed_down = false
interval = 10
